### ISSUE TITLE
Doesn't understand selector lists

### ISSUE THREAD

**Issue by hjri** [rstacruz/stylelint-rscss#13]
here's stylelint config:
```json
    "rscss/no-descendant-combinator": false,
    "rscss/class-format": [
      true,
      {
        "component": "pascal-case",
        "variant": "^-[a-z]\\w+",
        "element": "^[a-z]\\w+",
        "helper": "^fr-[a-z]\\w+"
      }
    ]
```
here's example code that breaks:
```scss
.Component {
  .elementA,
  .elementB {
     color: red
  }
}
```
It gives this error: `Invalid component name: '.elementB' (rscss/class-format) (css-stylelint)`
workaround is to do this:
```scss
.Component {
  & .elementA,
  & .elementB {
     color: red
  }
}
```

both ways are equivalent and produce same code
